<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Blog
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: changelog.php 8442 2011-02-11 01:14:59Z john $
 * @author     John
 */
return array(
  '4.1.2' => array(
    'Api/Core.php' => 'Fixes issue where filtering blog by tag would give an error',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added configuration options to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'widgets/list-popular-blogs/Controller.php' => 'Added configuration options',
    'widgets/list-popular-blogs/index.tpl' => 'Changed to generic styles',
    'widgets/list-recent-blogs/Controller.php' => 'Added configuration options',
    'widgets/list-recent-blogs/index.tpl' => 'Changed to generic styles',
  ),
  '4.1.1' => array(
    'controllers/AdminSettingsController.php' => 'Newly created categories gets the correct owner id',
    'controllers/IndexController.php' => 'Does not try to populate privacy options if they do not exist on edit page',
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'externals/styles/main.css' => 'RTL improvements',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/categories.tpl' => 'Hides the owner id column when viewing categories',
    'views/scripts/index/view.tpl' => 'Fixed issue with building category list',
  ),
  '4.1.0' => array(
    '/application/languages/en/blog.csv' => 'Added phrases',
    'controllers/AdminLevelController.php' => 'Added notice on form save',
    'controllers/AdminManageController.php' => 'Fixed issue with deletion',
    'controllers/AdminSettingsController.php' => 'Added notice on form save',
    'controllers/IndexController.php' => 'Fixed issue with pagination and searching for browse blogs page',
    'externals/images/nophoto_blog_thumb_icon.png' => 'Added',
    'externals/styles/main.css' => 'Added styles',
    'Form/Create.php' => 'Fixed issue with disabled privacy options',
    'Form/Delete.php' => 'Added',
    'Form/Search.php' => 'Fixed issue with disabled privacy options',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Menus.php' => 'Added share link to gutter menu',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pagination/item count limits to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/deleteselected.tpl' => 'Removed',
    'views/scripts/admin-manage/index.tpl' => 'Fixed issue with deletion',
    'views/scripts/index/delete.tpl' => 'Removed navigation',
    'views/scripts/index/index.tpl' => 'Fixed issue with pagination; fixed issue with UTF-8 truncation',
    'views/scripts/index/list.tpl' => 'Fixed issues with filtering',
    'views/scripts/index/manage.tpl' => 'Fixed issue with pagination; fixed issue with UTF-8 truncation',
    'views/scripts/index/view.tpl' => 'Fixed issues with filtering',
    'views/scripts/pagination/blogpagination.tpl' => 'Removed',
    'widgets/list-popular-blogs/Controller.php' => 'Added pagination/item count limit',
    'widgets/list-recent-blogs/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-blogs/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-blogs/index.tpl' => 'Added pagination/item count limit',
  ),
  '4.0.5' => array(
    'controllers/IndexController.php' => 'Added registered privacy type',
    'Form/Admin/Settings/Level.php' => 'Added registered privacy type',
    'Form/Create.php' => 'Added registered privacy type',
    'Model/Blog.php' => 'Different',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support; added registered privacy type',
    'settings/changelog.php' => 'Added',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/list.tpl' => 'Added missing css class to navigation',
  ),
  '4.0.4' => array(
    'controllers/IndexController.php' => 'Added localization to the archive list',
    'externals/styles/main.css' => 'Improved RTL support',
    'Form/Style.php' => 'Style tweak',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Fixed incorrect admin permissions for commenting',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/index.tpl' => 'Fixes error in blog when filtered by category',
    'views/scripts/index/view.tpl' => 'Fixes style problems in navigation',
    'widgets/list-recent-blogs/index.tpl' => 'Styled',
    'widgets/list-popular-blogs/index.tpl' => 'Styled',
    '/application/languages/en/blog.csv' => 'Added phrases',
  ),
  '4.0.3' => array(
    'controllers/IndexController.php' => 'Menus now use menu system; fixes for auth to allow moderation',
    'Plugin/Menus.php' => 'Menus now use menu system',
    'settings/content.php' => 'Fixed typo in popular blog name which prevented display',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.2-4.0.3.sql' => 'Added',
    'settings/my.sql' => 'Menus now use menu system; incremented version',
    'views/scripts/admin-level/index.tpl' => 'Added missing translation',
    'views/scripts/admin-manage/index.tpl' => 'Fixed view link to use slug; added missing translation; added correct locale date format',
    'views/scripts/admin-settings/categories.tpl' => 'Added missing translation',
    'views/scripts/admin-settings/index.tpl' => 'Added missing translation',
    'views/scripts/index/index.tpl' => 'Menus now use menu system',
    'views/scripts/index/list.tpl' => 'Menus now use menu system',
    'views/scripts/index/manage.tpl' => 'Menus now use menu system; added missing translation',
    'views/scripts/index/view/tpl' => 'Menus now use menu system',
    '/application/languages/en/blog.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'Api/Core.php' => 'Categories ordered by name',
    'controllers/AdminLevelController.php' => 'Various level settings fixes and enhancements',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
  ),
  '4.0.1' => array(
    'Api/Core.php' => 'Adjustment for trial',
    'controllers/AdminLevelController.php' => 'Fix for public level',
    'controllers/AdminSettingsController.php' => 'Source code formatting',
    'controllers/IndexController.php' => 'Fixed public permissions',
    'Form/Admin/Settings/Global.php' => 'Moved public permissions to public level settings',
    'Form/Admin/Settings/Level.php' => 'Moved public permissions to public level settings',
    'Plugin/Core.php' => 'Query optimization',
    'settings/manifest.php' => 'Incremented version',
    'views/scripts/admin-level/index.tpl' => 'Level change fix',
    'widgets/list-popular-blogs/Controller.php' => 'Fixed typo',
    'widgets/list-recent-blogs/Controller.php' => 'Fixed typo',
    'widgets/list-recent-blogs/index.tpl' => 'Styled',
  ),
) ?>