<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Video
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: changelog.php 8442 2011-02-11 01:14:59Z john $
 * @author     Jung
 */
return array(
  '4.1.2' => array(
    'Api/Core.php' => 'Fixed issue where encoding would fail on distributed hosting',
    'controllers/AdminSettingsController.php' => 'Updated utilities for newer versions of ffmpeg',
    'controllers/IndexController.php' => 'Code formatting',
    'externals/styles/main.css' => 'Remove old styles',
    'Form/Search.php' => 'Changed to GET',
    'Plugin/Job/Encode.php' => 'Fixed issue where encoding would fail on distributed hosting',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added widgets',
    'settings/install.php' => 'Added preliminary layout code',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/utility.tpl' => 'Updated utilities for newer versions of ffmpeg',
    'views/scripts/index/browse.tpl' => 'Fixed pagination issue; fixed localization issues',
    'views/scripts/index/view.tpl' => 'Fixed category link',
    'widgets/list-popular-videos/Controller.php' => 'Added configuration options',
    'widgets/list-popular-videos/index.tpl' => 'Styles are now generic',
    'widgets/list-recent-videos/Controller.php' => 'Added configuration options',
    'widgets/list-recent-videos/index.tpl' => 'Styles are now generic',
    'widgets/show-also-liked/Controller.php' => 'Added',
    'widgets/show-also-liked/index.tpl' => 'Added',
    'widgets/show-same-poster/Controller.php' => 'Added',
    'widgets/show-same-poster/index.tpl' => 'Added',
    'widgets/show-same-tags/Controller.php' => 'Added',
    'widgets/show-same-tags/index.tpl' => 'Added',
  ),
  '4.1.1' => array(
    'controllers/AdminSettingsController.php' => 'Fixed issue with detection of ffmpeg path and newly created categories gets the correct owner id',
    'controllers/IndexController.php' => 'Blocks uploads of obvious scripting file extensions',
    'controllers/UploadController.php' => 'Removed',
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'externals/scripts/composer_video.js' => 'Fixed issue with disappearing Add Video text',
    'externals/styles/main.css' => 'Removed duplicate CSS rule in manage page for the video duration span element',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/categories.tpl' => 'Hides the owner id column when viewing categories',
    'views/scripts/upload/' => 'Removed',
  ),
  '4.1.0' => array(
    '/application/languages/en/video.csv' => 'Fixed phrases with stray double-quotes',
    'Api/Core.php' => 'Fixed issue with ratings; added job support',
    'controllers/AdminManageController.php' => 'Added option to cancel video encoding (only works before encoding starts)',
    'controllers/AdminSettingsController.php' => 'Added notice on form save',
    'controllers/IndexController.php' => 'Fixed issue with ratings; fixed issue with incrementing view count',
    'externals/images/nophoto_video_thumb_icon.png' => 'Added',
    'externals/scripts/composer_video.js' => 'Fixed issue with messages composer',
    'externals/styles/main.css' => 'Adjusted styles',
    'Form/Admin/Global.php' => 'Moved public view option to level settings',
    'Form/Edit.php' => 'Fixed issue with disabled privacy options',
    'Form/Video.php' => 'Fixed issue with disabled privacy options',
    'Model/Video.php' => 'Added object param to address z-index issues with IM',
    'Plugin/Job/Encode.php' => 'Added',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Task/Encode.php' => 'Removed',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pagination/item count limits to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.0rc1-4.0.0rc2.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.4-4.0.5.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_composeVideo.tpl' => 'Fixed issue with messages composer',
    'views/scripts/admin-manage/deleteselected.tpl' => 'Removed',
    'views/scripts/admin-manage/index.tpl' => 'Improvements',
    'views/scripts/index/manage.tpl' => 'Fixed UTF-8 truncation issue',
    'views/scripts/index/view.tpl' => 'UI improvements',
    'widgets/list-popular-videos/Controller.php' => 'Added pagination/item count limit',
    'widgets/list-recent-videos/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-videos/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-videos/index.tpl' => 'Added pagination/item count limit',
  ),
  '4.0.5' => array(
    'Api/Core.php' => 'Fixed video tag searches causing exceptions; fixed issue with duplicate results when viewing a tag',
    'controllers/AdminSettingsController.php' => 'Fixed problems with open_basedir and ffmpeg path verification/detection',
    'controllers/IndexController.php' => 'Added registered privacy type',
    'Form/Admin/Settings/Level.php' => 'Added registered privacy type',
    'Form/Edit.php' => 'Added registered privacy type',
    'Form/Video.php' => 'Added registered privacy type',
    'Model/Video.php' => 'Tweak to slug handling',
    'Plugin/Task/Encode.php' => 'Added notifications on failed encoding; fixed problems with open_basedir and ffmpeg path verification/detection; code formatting',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support',
    'settings/changelog.php' => 'Added',
    'settings/content.php' => 'Code formatting',
    'settings/install.php' => 'Fixed problems with open_basedir and ffmpeg path verification/detection',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Fixed missing category in encode task',
    'settings/my-upgrade-4.0.4-4.0.5.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/create.tpl' => 'Fixed issue with selecting tags from autosuggest',
    '/application/languages/en/video.csv' => 'Added missing phrases',
  ),
  '4.0.4' => array(
    'Api/Core.php' => 'Added the ability to search browse videos by search phrase',
    'controllers/AdminSettingsController.php' => 'Fixed warning message about ffmpeg when open_basedir enabled',
    'controllers/IndexController.php' => 'Fixed warning messages; added the ability to search browse videos by search phrase',
    'externals/styles/main.css' => 'Improved RTL support',
    'Form/Edit.php' => 'Removing deprecated code; fixed issue with incorrect auth checking',
    'Form/Search.php' => 'Added the ability to search browse videos by search phrase',
    'Plugin/Task/Encode.php' => 'Added progress reporting',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added; fixed typo',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added; added code to address typo',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_FancyUpload.tpl' => 'Added missing translation',
    'views/scripts/_formButtonCancel.tpl' => 'Removing deprecated code',
    'views/scripts/index/browse.tpl' => 'Improved RTL support',
    'views/scripts/index/view.tpl' => 'Improved RTL support',
    'views/scripts/upload/upload.tpl' => 'Added missing translation',
    'widgets/profile-videos/index.tpl' => 'Improved RTL support',
    '/application/languages/en/video.csv' => 'Added phrases',
  ),
  '4.0.3' => array(
    'controllers/IndexController.php' => 'Fixed activity privacy bug; fixed quote handling bug',
    'controllers/AdminSettingsController.php' => 'Show error message if FFMPEG path is invalid',
    'Form/Video.php' => 'Hides the privacy setting if there are no privacy set',
    'Plugin/Task/Encode.php' => 'Fixed activity privacy bug; Passes owner_id to storage system; Sets video to processing only after FFMPEG check passes',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_composeVideo.tpl' => 'Added missing translation',
    'views/scripts/admin-manage/index.tpl' => 'Added correct locale date format',
    'views/scripts/index/create.tpl' => 'Fixed unlimited quota bug',
    'views/scripts/index/manage.tpl' => 'Fixed unlimited quota bug',
    'views/scripts/index/view.tpl' => 'Added missing translation',
    'widgets/list-recent-videos/Controller.php' => 'No longer shows videos that failed or have not finished encoding',
    '/application/languages/en/video.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'Api/Core.php' => 'Categories ordered by name',
    'controllers/AdminSettingsController.php' => 'Various level settings fixes and enhancements',
    'controllers/IndexController.php' => 'Filter form now accepts GET requests',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'Plugin/Task/Encode.php' => 'Added Ffmpeg validation prior to running encode task.',
    'settings/install.php' => 'Checks for ffmpeg binary on install/upgrade',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
    'views/scripts/admin-manage/index.tpl' => 'Uses displayname instead of username',
    'views/scripts/index/browse.tpl' => 'Pagination control keeps filter form params',
  ),
  '4.0.1' => array(
    'Api/Core.php' => 'Adjustments for trial',
    'controllers/AdminSettingsController.php' => 'Fixed problem in level select',
    'controllers/IndexController.php' => 'Better cleanup of temporary files and fixed public permissions',
    'controllers/UploadController.php' => 'Fixed missing level permission check',
    'Plugin/Core.php' => 'Query optimization',
    'Plugin/Task/Encode.php' => 'Better cleanup of temporary files',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.0-4.0.1.sql' => 'Added',
    'settings/my.sql' => 'Added comment_count column to engine4_video_videos table',
  ),
) ?>