<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Album
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: changelog.php 8442 2011-02-11 01:14:59Z john $
 * @author     Jung
 */
return array(
  '4.1.2' => array(
    '/application/languages/en/album.csv' => 'Added phrases',
    'controllers/AlbumController.php' => 'Added ability to order photos in an album',
    'controllers/PhotoController.php' => 'Added ability to edit title/description of photo through the view page',
    'externals/styles/main.css' => 'Added styles',
    'Form/Album/EditPhoto.php' => 'Added',
    'Form/Photo/Delete.php' => 'Added',
    'Form/Photo/Edit.php' => 'Refactored',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added new widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.1-4.1.2.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/album/editphotos.tpl' => 'Fixed missing closing tag',
    'views/scripts/album/view.tpl' => 'Added ability to order photos in an album',
    'views/scripts/photo/delete.tpl' => 'Added',
    'views/scripts/photo/edit.tpl' => 'Added',
    'views/scripts/photo/view.tpl' => 'Use AJAX friend list retrieval by default on photo tagging',
    'widgets/list-popular-albums/Controller.php' => 'Added',
    'widgets/list-popular-albums/index.tpl' => 'Added',
    'widgets/list-popular-photos/Controller.php' => 'Added',
    'widgets/list-popular-photos/index.tpl' => 'Added',
    'widgets/list-recent-albums/Controller.php' => 'Added',
    'widgets/list-recent-albums/index.tpl' => 'Added',
    'widgets/list-recent-photos/Controller.php' => 'Added',
    'widgets/list-recent-photos/index.tpl' => 'Added',
  ),
  '4.1.1' => array(
    'Api/Core.php' => 'Changes for storage system modifications; fixed incorrect storage system params (in Model/Photo.php)',
    'controllers/AdminSettingsController.php' => 'Newly created categories gets the correct owner id',
    'controllers/AlbumController.php' => 'Moved photo handling into a setPhoto() method',
    'controllers/IndexController.php' => 'Moved photo handling into a setPhoto() method',
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'Model/Album.php' => 'Changes for storage system modifications',
    'Model/Photo.php' => 'Changes for storage system modifications; moved photo handling into a setPhoto() method',
    'Plugin/Core.php' => 'Changes for storage system modifications; moved photo handling into a setPhoto() method',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.0-4.1.1.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/categories.tpl' => 'Hides the owner id column when viewing categories',
  ),
  '4.1.0' => array(
    '/application/languages/en/album.csv' => 'Added phrases',
    'controllers/AdminLevelController.php' => 'Added notice on form save',
    'controllers/AdminManageController.php' => 'Fixed issue with album deletion',
    'controllers/AdminSettingsController.php' => 'Added notice on form save',
    'controllers/AlbumController.php' => 'Fixed UI issue with smoothboxes',
    'controllers/IndexController.php' => 'Improved search function on manage page',
    'externals/styles/main.css' => 'Fixed minor style issues',
    'Form/Album.php' => 'Fixed issue with disabled privacy options',
    'Form/Album/Edit.php' => 'Fixed issue with disabled privacy options',
    'Model/Photo.php' => 'Fixed issue with deleting profile photos when the album plugin is not installed',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pagination/item count limits to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/delete.tpl' => 'Added',
    'views/scripts/admin-manage/index.tpl' => 'Adjusted return link',
    'views/scripts/index/browse.tpl' => 'Fixed UTF-8 truncation issue',
    'views/scripts/index/manage.tpl' => 'Added filter form',
    'views/scripts/index/upload.tpl' => 'Hides irrelevant form values when adding photos to existing album',
    'views/scripts/photo/view.tpl' => 'Added comment for AJAX friend retrieval',
    'widgets/profile-albums/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-albums/index.tpl' => 'Added pagination/item count limit',
  ),
  '4.0.5' => array(
    'controllers/AdminLevelController.php' => 'Fixed bug preventing switching level',
    'controllers/AlbumController.php' => 'Added registered privacy type',
    'Form/Admin/Settings/Level.php' => 'Added registered privacy type',
    'Form/Album.php' => 'Added registered privacy type',
    'Form/Album/Edit.php' => 'Added registered privacy type',
    'Model/Album.php' => 'Removed redundant search columns',
    'Model/Photo.php' => 'Removed redundant search columns',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support; added registered privacy type',
    'settings/changelog.php' => 'Added',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-level/index.tpl' => 'Fixed bug preventing switching level',
    'views/scripts/album/view.tpl' => 'Fixes rare error with empty titles',
  ),
  '4.0.4' => array(
    'controllers/AlbumController.php' => 'Tweak for message photos',
    'externals/styles/main.css' => 'Improved RTL support',
    'Model/DbTable/Albums.php' => 'Tweak for message photos',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_composePhoto.tpl' => 'Added missing translation',
    'views/scripts/_formButtonCancel.tpl' => 'Removing deprecated code',
    'views/scripts/photo/view.tpl' => 'Added missing translation',
  ),
  '4.0.3' => array(
    'controllers/IndexController.php' => 'Quick navigation uses menu system',
    'Plugin/Menus.php' => 'Better auth handling for menus',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.2-4.0.3.sql' => 'Added',
    'settings/my.sql' => 'Added album menus to the menu editor; quick navigation uses menu system; incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Correct locale date formatting; added missing translation',
    'views/scripts/admin-settings/categories.tpl' => 'Added missing translation',
    'views/scripts/admin-settings/index.tpl' => 'Added missing translation',
    'views/scripts/index/browse.tpl' => 'Quick navigation uses menu system',
    'views/scripts/index/manage.tpl' => 'Quick navigation uses menu system',
    '/application/languages/en/album.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'Api/Core.php' => 'Categories ordered by name',
    'controllers/AdminLevelController.php' => 'Various level settings fixes and enhancements',
    'controllers/AlbumController.php' => 'Fixed activity privacy rebinding problem',
    'controllers/IndexController.php' => 'Fixed problem setting the category in browse',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'Model/Photo.php' => 'Added missing parent::_postDelete(), could have caused issues with orphaned rows',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
    '/application/languages/en/album.csv' => 'Fix activity feed translations',
  ),
  '4.0.1' => array(
    'Api/Core.php' => 'Cleanup of temporary files; adjustment for trial',
    'controllers/AlbumController.php' => 'Fixed missing level permissions check',
    'controllers/PhotoController.php' => 'Fixed missing level permissions check; added view count support',
    'Form/Admin/Level.php' => 'Source code formatting',
    'Plugin/Core.php' => 'Query optimization',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.0-4.0.1.sql' => 'Added',
    'settings/my.sql' => 'Added missing view_count and comment_count columns to the engine4_album_photos table',
  ),
) ?>