<?php
/**
 * SocialEngine
 *
 * @category   Application_Core
 * @package    Activity
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: changelog.php 8943 2011-05-16 21:52:41Z john $
 * @author     John
 */
return array(
  '4.1.5' => array(
    'controllers/IndexController.php' => 'Fixed issue of feed not rendering when plugins get disabled',
    'Model/Action.php' => 'Fixed issue of feed not rendering when plugins get disabled',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_activityText.tpl' => 'Fixed rare issue of who liked a comment not rendering',
    'widget/feed/index.tpl' => 'Fixed issue of feed not rendering when plugins get disabled',
    'widgets/feed/Controller.php' => 'Fixed issue of feed not rendering when plugins get disabled',
  ),
  '4.1.4' => array(
    'externals/styles/main.css' => 'Added styles',
    'externals/styles/mobile.css' => 'Added',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_activityText.tpl' => 'Moved ul from _activityText.tpl; Added li\'s around action link to help with developing themes; Delete link removed from comments in mobile',
    'widgets/feed/index.tpl' => 'Moved ul to _activityText.tpl',
  ),
  '4.1.3' => array(
    '/application/languages/en/activity.csv' => 'Added phrases',
    'controllers/AdminSettingsController.php' => 'Added controller for configuring default enabled notifications',
    'controllers/IndexController.php' => 'Fixed issue of undefined post_fail variable being logged; Activity post now sends member profile photo to Facebook if there is no attached image',
    'Model/DbTable/Actions.php' => 'Modifications to fix issues with activity privacy on profile pages',
    'Model/DbTable/NotificationTypes.php' => 'Added ability to configure default enabled notification types',
    'Plugin/Core.php' => 'Modifications to fix issues with activity privacy on profile pages',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.2-4.1.3.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_activityText.tpl' => 'Fixed issue with moderators not being able to delete comments',
    'views/scripts/admin-settings/notifications.tpl' => 'Added',
    'views/scripts/notifications/index.tpl' => 'Added try/catch around requests',
  ),
  '4.1.2' => array(
    'controllers/IndexController.php' => 'Added the ability to like comments',
    'externals/scripts/core.js' => 'Added the ability to like comments',
    'externals/styles/main.css' => 'Added styles',
    'Model/Comment.php' => 'Added',
    'Model/DbTable/Comments.php' => 'Added the ability to like comments',
    'Model/DbTable/Likes.php' => 'Added the ability to like comments',
    'Model/Like.php' => 'Added',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added preliminary layout enhancements',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.1-4.1.2.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_activityText.tpl' => 'Added the ability to like comments',
    'widget/feed/index.tpl' => 'Added the ability to like comments; Escaping translation for the phrase "Post Something..."',
  ),
  '4.1.1' => array(
    '/application/languages/en/activity.csv' => 'Fixed minor admin panel description typos',
    'controllers/AdminSettingsController.php' => 'Removed unnecessary route',
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'externals/styles/main.css' => 'RTL improvements',
    'Model/DbTable/Actions.php' => 'Added code to facilitate feed filtering',
    'Model/DbTable/ActionTypes.php' => 'Added code to facilitate feed filtering',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.5p1-4.1.0.sql' => 'Fixed typo',
    'settings/my-upgrade-4.1.0-4.1.1.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/general.tpl' => 'Removed unnecessary route',
    'views/scripts/admin-settings/index.tpl' => 'Added',
  ),
  '4.1.0' => array(
    '/application/languages/en/activity.csv' => 'Repairing double-quotes in language file',
    'controllers/AdminSettingsController.php' => 'Added notice when saving forms',
    'controllers/IndexController.php' => 'Facebook status are now run though html_entity_decode',
    'Form/Admin/Settings/ActionType.php' => 'Improved descriptions',
    'Form/Admin/Settings/General.php' => 'Moved type settings to another page',
    'Model/Action.php' => 'getHref() now returns proper link',
    'Model/DbTable/Actions.php' => 'Added back-end support for filtering the feed by item type',
    'Plugin/Core.php' => 'Allowed User_Model_User actions to be included into network stream',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5p1-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'View/Helper/Activity.php' => 'Fixed feed item moderation',
    'views/scripts/_activityText.tpl' => 'Fixed feed item moderation',
    'views/scripts/admin-settings/general.tpl' => 'Improved descriptions',
    'views/scripts/admin-settings/types.tpl' => 'Improved descriptions',
    'widgets/feed/Controller.php' => 'Fixed issue with selecting incorrect number of items',
    'widgets/feed/index.tpl' => 'Fixed issue with posting a status on mobile devices, such as the iPad and iPhone',
  ),
  '4.0.5p1' => array(
    'Model/Action.php' => 'Fixed issue where actions get indexed in global search',
    'Model/Notification.php' => 'Fixed issue where actions get indexed in global search',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.5-4.0.5p1.sql' => 'Added',
    'views/scripts/index/delete.tpl' => 'Fixed issue with incorrect layout after post',
    'widgets/feed/Controller.php' => 'Fixed issue with too many action items being displayed; fixed issue with duplicate items being display when viewing a specific feed item',
  ),
  '4.0.5' => array(
    'Form/Admin/Settings/ActionType.php' => 'Added',
    'Form/Admin/Settings/General.php' => 'Added more feed length options',
    'Model/DbTable/ActionSettings.php' => 'Fixes issues where disabled action types still show in the user settings page',
    'Model/DbTable/ActionTypes.php' => 'Fixes issues where disabled action types still show in the user settings page',
    'Model/DbTable/Notifications.php' => 'Added more variables for mail templates',
    'Model/Helper/Item.php' => 'Added handling for missing href',
    'Model/Helper/Translate.php' => 'Added no translate bit',
    'Model/Notification.php' => 'Typo in error message',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support',
    'View/Helper/ActivityLoop.php' => 'Can now accept an array in addition to a rowset',
    'controllers/AdminSettingsController.php' => 'Added action for configuring action types',
    'controllers/IndexController.php' => 'Added auth for composer plugins; fixed context switch issues',
    'externals/images/nophoto_action_thumb_icon.png' => 'Added',
    'settings/changelog.php' => 'Added',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_activityText.tpl' => 'Moved some processing of actions to controller; fixed some errors when items are missing',
    'views/scripts/admin-settings/types.tpl' => 'Added',
    'views/scripts/notifications/index.tpl' => 'Fixed incorrect url that would prevent view more from working',
    'widgets/feed/Controller.php' => 'Improved user limit handling, should display the full feed length in most cases now',
    'widgets/feed/index.tpl' => 'Fixes composer javascript when feed is empty',
  ),
  '4.0.4' => array(
    'controllers/AdminSettingsController.php' => 'Fixed problem with disabling or enabling activity feed item types',
    'controllers/NotificationsController.php' => 'Moved pulldown update here',
    'externals/styles/main.css' => 'Improved RTL support',
    'Form/Admin/Settings/General.php' => 'Fixed problem with disabling or enabling activity feed item types',
    'Model/Helper/Body.php' => 'Added container around post body for future improved RTL support',
    'Plugin/Core.php' => 'Fixed issues with privacy in the feed when content is hidden from the public by admin settings',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_formActivityButton.tpl' => 'Removed deprecated code',
    'views/scripts/notifications/pulldown.tpl' => 'Moved pulldown update here',
    'views/scripts/widget/*' => 'Removing deprecated code',
    'widgets/feed/index.tpl' => 'Added missing translation; fixed smoothbox binding on view more; fixed incorrect inclusion of javascript files',
    '/application/languages/en/activity.csv' => 'Added phrases',
  ),
  '4.0.3' => array(
    'Model/DbTable/NotificationTypes.php' => 'Fixed bug with missing notification emails',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    '/application/languages/en/activity.csv' => 'Added phrases',
  ),
  '4.0.2p1' => array(
    'Model/Helper/Item.php' => 'Fixed pluralization of updates text',
    'settings/manifest.php' => 'Incremented version',
  ),
  '4.0.2' => array(
    'controllers/IndexController.php' => 'Added missing authorization checks',
    'Model/DbTable/Actions.php' => 'Fixed bad IN clauses in query',
    'Model/Helper/Item.php' => 'Adds translation of item text in update notifications',
    'Plugin/Core.php' => 'Fixed several privacy issues',
    'settings/manifest.php' => 'Incremented version',
    'views/scripts/_activityText.tpl' => 'Added missing authorization checks',
    '/application/languages/en/activity.csv' => 'Adds translation of item text in update notifications',
  ),
  '4.0.1' => array(
    'Model/DbTable/Notifications.php' => 'Fixes problem with notifications from disabled modules',
    'Plugin/Core.php' => 'Fixes problem with properly detecting the page subject and handles items without parents properly',
    'settings/manifest.php' => 'Incremented version',
    'views/scripts/notifications/index.tpl' => 'Fixes problem with notifications from disabled modules',
    'widgets/list-requests/index.tpl' => 'Fixes problem with notifications from disabled modules',
  ),
) ?>