<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Event
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: changelog.php 8474 2011-02-16 01:33:15Z john $
 * @author     Sami
 */
return array(
  '4.1.2' => array(
    '/application/languages/en/event.csv' => 'Added phrases',
    'Api/Core.php' => 'Fixed PHP notices about undefined indexes',
    'externals/styles/main.css' => 'Added styles',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added widgets',
    'settings/install.php' => 'Added preliminary layout editor enhancements',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.1-4.1.2.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/topic/view.tpl' => 'Added CSS classes to owner posts',
    'widgets/list-popular-events/Controller.php' => 'Added',
    'widgets/list-popular-events/index.tpl' => 'Added',
    'widgets/list-recent-events/Controller.php' => 'Added',
    'widgets/list-recent-events/index.tpl' => 'Added',
    'widgets/profile-events/Controller.php' => 'Added order by statement for sorting',
  ),
  '4.1.1' => array(
    'Api/Core.php' => 'Upcoming events are now filtered by starttime and not endtime',
    'controllers/PostController.php' => 'Fixed issue with users being unable to edit/delete discussion posts',
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'Model/Photo.php' => 'Changes for storage system modifications',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/create.tpl' => 'Fixed short tag',
  ),
  '4.1.0' => array(
    '/application/languages/en/event.csv' => 'Fixed phrases with stray double-quotes',
    'Api/Core.php' => 'Added filtering options',
    'controllers/AdminManageController.php' => 'Fixed pagination issue',
    'controllers/AdminSettingsController.php' => 'Added notice on form save',
    'controllers/EventController.php' => 'Fixed issue with deletion; fixed UI issue with smoothboxes',
    'controllers/IndexController.php' => 'Added navigation to menu system',
    'controllers/MemberController.php' => 'Fixed issue with joining and leaving; fixed issue with checking approval setting; fixed incorrect notification',
    'controllers/PhotoController.php' => 'Fixed issue with view privacy',
    'controllers/PostController.php' => 'Added form save notice; fixed issue with post deletion and updating parent topic post count',
    'controllers/ProfileController.php' => 'Silencing notices caused by content system',
    'controllers/TopicController.php' => 'Fixed issue preventing admins from editing/deleting posts',
    'externals/styles/main.css' => 'Added styles for event join activity feed item',
    'Form/Create.php' => 'Fixed issue with disabled privacy options',
    'Form/Delete.php' => 'Fixed UI issue',
    'Form/Edit.php' => 'Fixed issue with disabled privacy options',
    'Form/Filter/Browse.php' => 'Adjusting filtering options',
    'Form/Filter/Manage.php' => 'Adjusting filtering options',
    'Form/Member/Join.php' => 'Changed default form value',
    'Form/Post/Edit.php' => 'Added htmlspecialchars()',
    'Form/Topic/Create.php' => 'Added htmlspecialchars()',
    'Form/Topic/Delete.php' => 'Fixed UI issue',
    'Form/Topic/Rename.php' => 'Fixed UI issue',
    'Model/Event.php' => 'Fixed issue with getting the awaiting reply member count; added truncation to getDescription()',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Menus.php' => 'Added navigation to menu system',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pagination/item count limits to widgets',
    'settings/install.php' => 'Fixed issue where widgets were placed into the wrong parent on install',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Improved language',
    'views/scripts/event/delete.tpl' => 'UI improvements',
    'views/scripts/event/edit.tpl' => 'Added code to prevent end date < start date',
    'views/scripts/index/browse.tpl' => 'Added navigation to menu system',
    'views/scripts/index/create.tpl' => 'Added navigation to menu system',
    'views/scripts/index/manage.tpl' => 'Added navigation to menu system',
    'views/scripts/photo/upload.tpl' => 'UI improvements',
    'views/scripts/photo/view.tpl' => 'UI improvements',
    'views/scripts/topic/view.tpl' => 'UI improvements; fixes issue with automatically enabling links; fixed issue preventing admins from editing/deleting posts',
    'widgets/home-upcoming/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-discussions/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-events/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-events/index.tpl' => 'Added pagination/item count limit',
    'widgets/profile-members/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-members/index.tpl' => 'Added pagination/item count limit',
    'widgets/profile-photos/Controller.php' => 'Added pagination/item count limit',
  ),
  '4.0.5' => array(
    'controllers/IndexController.php' => 'Fixed errors caused by disabled action types',
    'controllers/MemberController.php' => 'Added support for missing action and notification types; join form now shows RSVP options',
    'controllers/PostController.php' => 'Improved auth handling',
    'controllers/TopicController.php' => 'Added topic watching support',
    'controllers/WidgetController.php' => 'Added notification request support',
    'externals/images/nophoto_event_thumb_icon.png' => 'Changed',
    'externals/images/unwatch.png' => 'Added',
    'externals/images/watch.png' => 'Added',
    'externals/styles/main.css' => 'Added styles; fixed style issue in topic view list',
    'Form/Create.php' => 'Added missing .jpeg extension to allowed file types',
    'Form/Edit.php' => 'Added missing .jpeg extension to allowed file types',
    'Form/Member/Join.php' => 'Removed token',
    'Form/Member/Reject.php' => 'Removed token',
    'Form/Post/Create.php' => 'Added topic watching support',
    'Form/Topic/Create.php' => 'Added topic watching support',
    'Model/DbTable/TopicWatches.php' => 'Added',
    'Model/Photo.php' => 'Improved checks on file deletion',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support',
    'settings/changelog.php' => 'Added',
    'settings/content.php' => 'Added support for configuring number of events displayed on the Upcoming Events widget',
    'settings/install.php' => 'Code formatting',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.4-4.0.5.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Fixed link to owner\'s profile',
    'views/scripts/index/browse.tpl' => 'Fixed issue with extra parameter in url',
    'views/scripts/index/manage.tpl' => 'Fixed issue with extra parameter in url',
    'views/scripts/topic/view.tpl' => 'Added topic watching support; fixed issue with quoting posts conataing quotes',
    'views/scripts/widget/request-event.tpl' => 'Added',
    'widgets/home-upcoming/Controller.php' => 'Change filter from start time to end time to display ongoing events',
    'widgets/home-upcoming/index.tpl' => 'Displays ongoing events',
    '/application/languages/en/event.csv' => 'Added missing phrases',
  ),
  '4.0.4' => array(
    'controllers/EventController.php' => 'Fixes timezone issues; fixed category ordering',
    'controllers/IndexController.php' => 'Fixes timezone issues; fixed category ordering',
    'controllers/MemberController.php' => 'Added RSVP select when joining an event',
    'externals/styles/main.css' => 'Improved RTL support',
    'Form/Rsvp.php' => 'Code cleanup',
    'Form/Member/*' => 'Fixes smoothbox problems on failed form validation',
    'Model/Event.php' => 'Added awaiting reply RSVP type',
    'Plugin/Core.php' => 'Fixed issues with privacy in the feed when content is hidden from the public by admin settings',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/install.php' => 'Group page should not be considered a custom page',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added; fixed custom page setting',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/widget' => 'Removed deprecated code',
    'views/scripts/index/browse.tpl' => 'Improved localization support; fixes hiding of filter form when options return no results',
    'views/scripts/index/create.tpl' => 'Removed deprecated code',
    'views/scripts/index/manage.tpl' => 'Improved localization support',
    'views/scripts/photo/view.tpl' => 'Added missing translation',
    'widgets/profile-info/index.tpl' => 'Improved localization support',
    'widgets/profile-members/index.tpl' => 'Added awaiting reply RSVP type',
    '/application/languages/en/event.csv' => 'Added missing phrases',
  ),
  '4.0.3' => array(
    'controllers/AdminSettingsController.php' => 'Tweak for public level',
    'controllers/IndexController.php' => 'Ordering categories by name',
    'externals/styles/main.css' => 'Styles for RSVP in member list',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Added correct locale date format',
    'widgets/profile-members/index.tpl' => 'Added display of member RSVP',
    '/application/languages/en/event.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'Api/Core.php' => 'Categories ordered by name',
    'controllers/AdminSettingsController.php' => 'Various level settings fixes and enhancements',
    'controllers/EventController.php' => 'Various level settings fixes and enhancements',
    'controllers/IndexController.php' => 'Various level settings fixes and enhancements',
    'Form/Create.php' => 'Various level settings fixes and enhancements',
    'Form/Edit.php' => 'Various level settings fixes and enhancements',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'Plugin/Core.php' => 'Added activity stream index type',
    'settings/content.php' => 'Added configuration options for Upcoming Events widget',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
    'widgets/home-upcoming/Controller.php' => 'Added configuration options for Upcoming Events widget',
    'widgets/profile-events/Controller.php' => 'Added parent check',
  ),
  '4.0.1' => array(
    'Api/Core.php' => 'Better cleanup of temporary files',
    'controllers/AdminSettingsController.php' => 'Fixed problem in level select',
    'controllers/EventController.php' => 'Added level permission for styles',
    'controllers/PhotoController.php' => 'Added view count support',
    'controllers/TopicController.php' => 'Added view count support',
    'Form/Admin/Level.php' => 'Added level permission for styles',
    'Model/Event.php' => 'Better cleanup of temporary files',
    'Plugin/Core.php' => 'Query optimization; fixed typo that would cause problem on user deletion',
    'Plugin/Menus.php' => 'Added level permission for styles',
    'settings/manifest.php' => 'Incremented version; fixed typo',
    'settings/my-upgrade-4.0.0-4.0.1.sql' => 'Added',
    'settings/my.sql' => 'Added view_count and comment_count columns to engine4_event_photos table; added view_count column to engine4_event_topics table; added default permissions for style permission',
  ),
) ?>